'use client'

import React, { useState } from 'react'
import {
  Download, FileText, Zap, Copy, TrendingDown,
  HardDrive, CheckCircle2, Calendar, Eye,
  Printer, Building2, User, Clock, AlertTriangle, ShieldCheck
} from 'lucide-react'
import toast from 'react-hot-toast'
import Modal from '@/components/ui/Modal'
import LoadingSpinner from '@/components/ui/LoadingSpinner'
import PageHeader from '@/components/layout/PageHeader'
import MetricCard from '@/components/ui/MetricCard'
import { useStorageData } from '@/context/StorageDataContext'
import { useAuth } from '@/context/AuthContext'
import { saveReportRecord } from '@/lib/services/authService'
import type { UserReportRecord } from '@/types/auth'
import clsx from 'clsx'

export default function ReportsPage() {
  const { analysisResult, records, dataSourceName, hasData } = useStorageData()
  const { user } = useAuth()

  const [generating, setGenerating] = useState(false)
  const [reportStep, setReportStep] = useState(0)
  const [previewOpen, setPreviewOpen] = useState(false)
  const [activeReport, setActiveReport] = useState<UserReportRecord | null>(null)

  // Derive findings
  const mostUsedFileType = analysisResult.byFileType[0]?.name || 'N/A'
  const mostUsedCategoryStorage = analysisResult.byFileType[0]?.storageGB || 0
  const mostUsedBucket = analysisResult.byBucket[0]?.name || 'N/A'
  const leastActiveCategory = analysisResult.byFileType[analysisResult.byFileType.length - 1]?.name || 'N/A'
  const largeFilesCount = records.filter(r => r.isLarge).length
  const archiveCandidatesCount = records.filter(r => r.storageClass === 'STANDARD' && (r.isInactive || r.isHighlyInactive)).length

  function handleCompileReport() {
    if (!hasData) {
      toast.error('No dataset loaded to compile report from.')
      return
    }

    setGenerating(true)
    setReportStep(1)

    setTimeout(() => setReportStep(2), 300)
    setTimeout(() => setReportStep(3), 600)
    setTimeout(() => {
      setGenerating(false)
      const newReport: UserReportRecord = {
        id: `rep_${Date.now()}`,
        userId: user?.id || 'guest',
        companyName: user?.companyName || 'NovaTech Solutions',
        userName: user?.name || 'Alex Rivera',
        reportTitle: `Storage Usage & Cost Audit (${new Date().toLocaleDateString('en-GB')})`,
        generatedAt: new Date().toISOString(),
        totalStorageGB: analysisResult.totalStorageGB,
        totalFiles: analysisResult.totalObjects,
        currentMonthlyCost: analysisResult.currentMonthlyCost,
        potentialMonthlySavings: analysisResult.potentialMonthlySavings,
        potentialAnnualSavings: analysisResult.potentialAnnualSavings,
        optimizationScore: analysisResult.optimizationScore,
        summaryText: `Storage audit compiled for ${user?.companyName || 'Workspace'}. ${analysisResult.totalObjects} objects analyzed across storage classes.`
      }

      saveReportRecord(newReport)
      setActiveReport(newReport)
      setPreviewOpen(true)

      toast.success('Storage Audit Report compiled and saved!')
    }, 900)
  }

  function handleExportReportCSV() {
    let csv = "CLOUDCUT STORAGE USAGE & COST AUDIT REPORT\n"
    csv += `Company Name:,"${user?.companyName || 'CloudCut Client'}"\n`
    csv += `Generated By:,"${user?.name || 'Customer'}"\n`
    csv += `Audit Date:,"${new Date().toISOString()}"\n`
    csv += `Dataset:,"${dataSourceName}"\n\n`

    csv += "--- STORAGE SUMMARY ---\n"
    csv += `Total Files Indexed:,${analysisResult.totalObjects}\n`
    csv += `Total Storage Managed (GB):,${analysisResult.totalStorageGB}\n`
    csv += `Average File Size (GB):,${analysisResult.averageFileSizeGB}\n`
    csv += `Buckets Monitored:,${analysisResult.byBucket.length}\n`
    csv += `Current Monthly Cost (INR):,${analysisResult.currentMonthlyCost}\n`
    csv += `Potential Monthly Savings (INR):,${analysisResult.potentialMonthlySavings}\n`
    csv += `Optimization Health Score:,${analysisResult.optimizationScore}/100\n\n`

    csv += "--- CATEGORY BREAKDOWN ---\n"
    csv += "Category,Storage (GB),Percentage,Cost (INR)\n"
    analysisResult.byFileType.forEach(f => {
      csv += `"${f.name}",${f.storageGB},${f.percentage},${f.cost}\n`
    })

    const csvContent = "data:text/csv;charset=utf-8," + encodeURIComponent(csv)
    const link = document.createElement("a")
    link.setAttribute("href", csvContent)
    link.setAttribute("download", `CloudCut_Audit_Report_${user?.companyName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    toast.success('Downloaded Report CSV!')
  }

  return (
    <div className="space-y-6 w-full min-w-0 pb-12">
      <PageHeader
        title="Storage & Cost Reports"
        subtitle="Generate and download audit reports documenting usage, spend, and optimization targets."
        actions={
          <div className="flex items-center gap-2">
            <button
              onClick={handleExportReportCSV}
              disabled={!hasData}
              className="btn-secondary text-xs"
            >
              <Download className="w-3.5 h-3.5" />
              Export CSV
            </button>
            <button
              onClick={handleCompileReport}
              disabled={generating || !hasData}
              className="btn-primary text-xs"
            >
              <FileText className="w-3.5 h-3.5" />
              {generating ? 'Compiling Audit...' : 'Generate New Report'}
            </button>
          </div>
        }
      />

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          title="Monitored Storage"
          value={analysisResult.totalStorageGB >= 1000 ? `${(analysisResult.totalStorageGB / 1000).toFixed(2)} TB` : `${analysisResult.totalStorageGB} GB`}
          subtitle={`${analysisResult.totalObjects} objects analyzed`}
          icon={<HardDrive className="w-4 h-4 text-slate-600" />}
        />

        <MetricCard
          title="Current Monthly Cost"
          value={`₹${analysisResult.currentMonthlyCost.toLocaleString('en-IN')}`}
          subtitle="Baseline spend projection"
          icon={<Clock className="w-4 h-4 text-slate-600" />}
        />

        <MetricCard
          title="Recoverable Savings"
          value={`₹${analysisResult.potentialMonthlySavings.toLocaleString('en-IN')}`}
          change={`${analysisResult.savingsPercentage}%`}
          changeType="positive"
          changeLabel="recoverable"
          icon={<TrendingDown className="w-4 h-4 text-emerald-600" />}
        />

        <MetricCard
          title="Health Score"
          value={`${analysisResult.optimizationScore} / 100`}
          subtitle="Efficiency assessment"
          icon={<ShieldCheck className="w-4 h-4 text-blue-600" />}
        />
      </div>

      {/* Report Generator Action Card */}
      <div className="card p-6 bg-slate-50 border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h3 className="text-base font-semibold text-slate-900">
            Standard 6-Part Storage Usage & Cost Audit
          </h3>
          <p className="text-xs text-slate-500 mt-0.5">
            Produces an executive report covering Storage Summary, Usage Analysis, Cost Projections, Waste Vectors, and Remediations.
          </p>
        </div>

        <button
          onClick={handleCompileReport}
          disabled={generating || !hasData}
          className="btn-primary"
        >
          <FileText className="w-4 h-4" />
          {generating ? 'Generating...' : 'Compile & Preview Report'}
        </button>
      </div>

      {/* 6-PART EXECUTIVE REPORT PREVIEW MODAL */}
      <Modal
        open={previewOpen}
        onClose={() => setPreviewOpen(false)}
        title="Storage Usage & Cost Audit Report"
        size="xl"
        footer={
          <div className="flex justify-between items-center w-full">
            <span className="text-xs text-slate-500">CloudCut Storage Audit</span>
            <div className="flex gap-2">
              <button onClick={() => setPreviewOpen(false)} className="btn-secondary text-xs">
                Close
              </button>
              <button onClick={handleExportReportCSV} className="btn-secondary text-xs">
                <Download className="w-3.5 h-3.5" />
                Download CSV
              </button>
              <button onClick={() => window.print()} className="btn-primary text-xs">
                <Printer className="w-3.5 h-3.5" />
                Print / Save PDF
              </button>
            </div>
          </div>
        }
      >
        <div className="space-y-6 text-slate-900 bg-white p-2">
          {/* Executive Header */}
          <div className="border-b border-slate-200 pb-4 flex justify-between items-start">
            <div>
              <span className="text-xs font-semibold text-blue-600 uppercase tracking-wider block">
                CloudCut FinOps Report
              </span>
              <h2 className="text-xl font-bold text-slate-900 mt-1">
                {user?.companyName} — Cloud Storage Audit
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Targeted infrastructure cost reduction and storage optimization
              </p>
            </div>
            <div className="text-right text-xs text-slate-500">
              <p>Generated: <strong>{new Date().toLocaleDateString('en-GB')}</strong></p>
              <p>Account: <strong>{user?.name}</strong></p>
              <p>Dataset: <strong>{dataSourceName}</strong></p>
            </div>
          </div>

          {/* Section 1: Storage Summary */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              1. Storage Summary
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3 rounded-md border border-slate-200">
              <div>
                <p className="text-[11px] text-slate-500">Total Files</p>
                <p className="text-base font-bold text-slate-900">{analysisResult.totalObjects.toLocaleString()}</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Total Storage</p>
                <p className="text-base font-bold text-slate-900">{analysisResult.totalStorageGB} GB</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Buckets</p>
                <p className="text-base font-bold text-slate-900">{analysisResult.byBucket.length}</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Storage Classes</p>
                <p className="text-base font-bold text-slate-900">{analysisResult.byStorageClass.length}</p>
              </div>
            </div>
          </div>

          {/* Section 2: Usage Analysis */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              2. Usage Analysis
            </h4>
            <div className="border border-slate-200 rounded-md p-3 text-xs space-y-1.5 bg-white">
              <p>• <strong>Most Used File Type:</strong> {mostUsedFileType} ({mostUsedCategoryStorage} GB allocated)</p>
              <p>• <strong>Primary Storage Container:</strong> {mostUsedBucket}</p>
              <p>• <strong>Least Active Storage Category:</strong> {leastActiveCategory}</p>
            </div>
          </div>

          {/* Section 3: Cost Analysis */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              3. Cost Analysis & Financial Impact
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3 rounded-md border border-slate-200">
              <div>
                <p className="text-[11px] text-slate-500">Monthly Cost</p>
                <p className="text-base font-bold text-slate-900">₹{analysisResult.currentMonthlyCost.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Optimized Cost</p>
                <p className="text-base font-bold text-slate-900">₹{analysisResult.potentialMonthlyCost.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Monthly Savings</p>
                <p className="text-base font-bold text-emerald-700">₹{analysisResult.potentialMonthlySavings.toLocaleString('en-IN')}</p>
              </div>
              <div>
                <p className="text-[11px] text-slate-500">Annual Savings</p>
                <p className="text-base font-bold text-emerald-700">₹{analysisResult.potentialAnnualSavings.toLocaleString('en-IN')}</p>
              </div>
            </div>
          </div>

          {/* Section 4: Optimization Findings */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              4. Optimization Findings & Waste Vectors
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-xs">
              <div className="p-2.5 bg-slate-50 border border-slate-200 rounded">
                <p className="text-[11px] text-slate-500">Duplicate Candidates</p>
                <p className="font-semibold text-slate-900 mt-0.5">{analysisResult.duplicateRecoverableStorageGB} GB</p>
              </div>
              <div className="p-2.5 bg-slate-50 border border-slate-200 rounded">
                <p className="text-[11px] text-slate-500">Inactive Storage (&gt;180d)</p>
                <p className="font-semibold text-slate-900 mt-0.5">{analysisResult.inactiveStorageGB} GB</p>
              </div>
              <div className="p-2.5 bg-slate-50 border border-slate-200 rounded">
                <p className="text-[11px] text-slate-500">Large Objects (&gt;10GB)</p>
                <p className="font-semibold text-slate-900 mt-0.5">{largeFilesCount} files</p>
              </div>
              <div className="p-2.5 bg-slate-50 border border-slate-200 rounded">
                <p className="text-[11px] text-slate-500">Archive Candidates</p>
                <p className="font-semibold text-slate-900 mt-0.5">{archiveCandidatesCount} files</p>
              </div>
            </div>
          </div>

          {/* Section 5: Highest Priority Recommendations */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              5. Priority Recommendations
            </h4>
            <div className="divide-y divide-slate-100 border border-slate-200 rounded-md overflow-hidden text-xs">
              {analysisResult.recommendations.slice(0, 3).map((r, i) => (
                <div key={r.id} className="p-2.5 flex justify-between items-center bg-white">
                  <div>
                    <span className="font-semibold text-slate-900">#{i + 1} {r.title}</span>
                    <p className="text-[11px] text-slate-500">{r.recommendedAction}</p>
                  </div>
                  <span className="font-semibold text-emerald-700 whitespace-nowrap ml-4">
                    +₹{r.estimatedMonthlySavings}/mo
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 6: Savings Summary & ROI */}
          <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-md text-xs text-emerald-900 flex justify-between items-center">
            <div>
              <p className="font-semibold">6. Savings Summary & Projected ROI</p>
              <p className="text-[11px] text-emerald-700">Estimated payback period: Immediate upon lifecycle transition.</p>
            </div>
            <div className="text-right">
              <span className="text-base font-bold text-emerald-700">
                ₹{analysisResult.potentialAnnualSavings.toLocaleString('en-IN')} / year
              </span>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  )
}
